services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    ports:
      - "3030:80"
    restart: always
    #environment:
    # Variables de entorno si hicieras customizaci√≥n (ninguna obligatoria por defecto)
    # e.g. BASE_PATH="/mi-ruta"
    # Volumen si quieres persistencia de archivos exportados, ajustes, etc:
    # volumes:
    #   - ./data/excalidraw:/app/data
    #   - ./data/excalidraw:/app/data