services:
  fastapi:
    build: backend
    container_name: fastapi-app
    expose:
      - "80"
    restart: always

  nginx:
    image: nginx:1.29-alpine
    container_name: nginx-proxy
    ports:
      - "82:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
    restart: always
